//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatos()
        {
            this.REL_Capacitaciones_Candidatos = new HashSet<REL_Capacitaciones_Candidatos>();
            this.REL_Competencias_Candidatos = new HashSet<REL_Competencias_Candidatos>();
            this.REL_Idioma_Candidatos = new HashSet<REL_Idioma_Candidatos>();
        }
    
        public int IdCandidato { get; set; }
        public int IdPersona_Candidatos { get; set; }
        public Nullable<int> PuestoAspirado_Candidatos { get; set; }
        public decimal SalarioAspirado_Candidatos { get; set; }
        public string Recomendacion_Candidatos { get; set; }
        public Nullable<bool> Estado_Candidatos { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Puestos Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_Capacitaciones_Candidatos> REL_Capacitaciones_Candidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_Competencias_Candidatos> REL_Competencias_Candidatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_Idioma_Candidatos> REL_Idioma_Candidatos { get; set; }
    }
}
