//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacitaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capacitaciones()
        {
            this.REL_Capacitaciones_Candidatos = new HashSet<REL_Capacitaciones_Candidatos>();
        }
    
        public int IdCapacitacion { get; set; }
        public string Descripcion_Capacitaciones { get; set; }
        public string Nivel_Capacitaciones { get; set; }
        public System.DateTime FechaDesde_Capacitaciones { get; set; }
        public System.DateTime FechaHasta_Capacitaciones { get; set; }
        public string Institucion_Capacitaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REL_Capacitaciones_Candidatos> REL_Capacitaciones_Candidatos { get; set; }
    }
}
