//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int IdEmpleado { get; set; }
        public int IdPersona_Empleados { get; set; }
        public System.DateTime FechaIngreso_Empleados { get; set; }
        public int IdPuesto_Empleados { get; set; }
        public decimal Salario_Empleados { get; set; }
        public Nullable<bool> Estado_Empleados { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Puestos Puestos { get; set; }
    }
}
