//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpLaborales
    {
        public int IdExpLaboral { get; set; }
        public int IdPersona_ExpLaboral { get; set; }
        public string Empresa_ExpLaborales { get; set; }
        public string PuestoOcupado_ExpLaborales { get; set; }
        public System.DateTime FechaDesde_ExpLaborales { get; set; }
        public System.DateTime FechaHasta_ExpLaborales { get; set; }
        public decimal Salario_ExpLaborales { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
