//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHHProyectoFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRHHEntities : DbContext
    {
        public RRHHEntities()
            : base("name=RRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidatos> Candidatos { get; set; }
        public virtual DbSet<Capacitaciones> Capacitaciones { get; set; }
        public virtual DbSet<Competencias> Competencias { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<ExpLaborales> ExpLaborales { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<REL_Capacitaciones_Candidatos> REL_Capacitaciones_Candidatos { get; set; }
        public virtual DbSet<REL_Competencias_Candidatos> REL_Competencias_Candidatos { get; set; }
        public virtual DbSet<REL_Idioma_Candidatos> REL_Idioma_Candidatos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
